server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #discovery:
        #locator:
          #enable: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
        uri: lb://cloud-payment-service
        #uri: http://localhost:8001 #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - After=2020-03-17T22:44:26.192+08:00[Asia/Shanghai]

      - id: payment_route2
        uri: lb://cloud-payment-service
        #uri: http://localhost:8001
        predicates:
        - Path=/payment/lb/** #断言,路径相匹配的进行路由
        - After=2020-03-18T22:52:26.192+08:00[Asia/Shanghai]
        #- Cookie=username,lj


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka