server:
  port: 80

eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 入驻地址
      # defaultZone: http://localhost:7001/eureka/
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#设置Feigen客户端超时时间（Feign默认支持Ribbon）
ribbon:
  #指的是建立连接使用的时间，适用于网络状态正常的情况下，连段连接使用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    com.atlj.springcloud.service: debug
